name: "Deploy staging"
"on":
  push:
    branches: [ main ]
jobs:
  build_and_deploy:
    if: ${{ github.event.repository.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Enable yarn cache"
        uses: c-hive/gha-yarn-cache@v2  # using cache

      - name: "Setup node@14"
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: "Install dependencies"
        run: |
          yarn set version 3.1.1
          yarn install

      - name: "Lint"
        run: |
          yarn lint --max-warnings 0

      - name: "Deploy target: goerli"
        run: yarn run ci:build:goerli
      - uses: matter-labs/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZKSYNC_DAPP_FORCED_EXIT }}"
          target: goerli
          projectId: forced-exit-staging
          channelID: live

      - name: "Deploy target: sepolia"
        run: yarn run ci:build:sepolia
      - uses: matter-labs/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZKSYNC_DAPP_FORCED_EXIT }}"
          target: sepolia
          projectId: forced-exit-staging
          channelID: live

      - name: "Deploy target: mainnet"
        run: yarn run ci:build:mainnet
      - uses: matter-labs/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZKSYNC_DAPP_FORCED_EXIT }}"
          target: sepolia
          projectId: forced-exit-staging
          channelID: live
